services:
  playwright-test:
    image: playwright
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright_docker
    volumes:
      - .:/app
    ports:
      - 5000:5000
    command: sh -c "npm run test || echo 'Tests failed'; npm run serve:report"